'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RuiKeZhong.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hand Wash
        '''Hand Wax
        '''Check Engine Fluid
        '''Detail Engine Compartment
        '''.
        '''</summary>
        Friend ReadOnly Property Exterior() As String
            Get
                Return ResourceManager.GetString("Exterior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hawaiian Mist
        '''Baby Powder
        '''Pine
        '''Country Floral
        '''Pina Colada
        '''Vanilla.
        '''</summary>
        Friend ReadOnly Property FragDesc() As String
            Get
                Return ResourceManager.GetString("FragDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.75
        '''1.50
        '''0.00
        '''2.25
        '''0.75
        '''2.00.
        '''</summary>
        Friend ReadOnly Property FragPrices() As String
            Get
                Return ResourceManager.GetString("FragPrices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fragrance
        '''Shampoo Carpets
        '''Interior Protection Coat
        '''Shampoo Upholstery
        '''.
        '''</summary>
        Friend ReadOnly Property Interior() As String
            Get
                Return ResourceManager.GetString("Interior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Standard
        '''Deluxe
        '''Executive
        '''Luxury.
        '''</summary>
        Friend ReadOnly Property PkgDesc() As String
            Get
                Return ResourceManager.GetString("PkgDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.50
        '''15.00
        '''35.00
        '''55.00
        '''.
        '''</summary>
        Friend ReadOnly Property PkgPrices() As String
            Get
                Return ResourceManager.GetString("PkgPrices", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
